import QtQuick 1.0

ListModel {
    ListElement { value: 00 }
    ListElement { value: 01 }
    ListElement { value: 02 }
    ListElement { value: 03 }
    ListElement { value: 04 }
    ListElement { value: 05 }
    ListElement { value: 06 }
    ListElement { value: 07 }
    ListElement { value: 08 }
    ListElement { value: 09 }
    ListElement { value: 10 }
    ListElement { value: 11 }
    ListElement { value: 12 }
    ListElement { value: 13 }
    ListElement { value: 14 }
    ListElement { value: 15 }
    ListElement { value: 16 }
    ListElement { value: 17 }
    ListElement { value: 18 }
    ListElement { value: 19 }
    ListElement { value: 20 }
    ListElement { value: 21 }
    ListElement { value: 22 }
    ListElement { value: 23 }
    ListElement { value: 24 }
    ListElement { value: 25 }
    ListElement { value: 26 }
    ListElement { value: 27 }
    ListElement { value: 28 }
    ListElement { value: 29 }
    ListElement { value: 30 }
    ListElement { value: 31 }
    ListElement { value: 32 }
    ListElement { value: 33 }
    ListElement { value: 34 }
    ListElement { value: 35 }
    ListElement { value: 36 }
    ListElement { value: 37 }
    ListElement { value: 38 }
    ListElement { value: 39 }
    ListElement { value: 40 }
    ListElement { value: 41 }
    ListElement { value: 42 }
    ListElement { value: 43 }
    ListElement { value: 44 }
    ListElement { value: 45 }
    ListElement { value: 46 }
    ListElement { value: 47 }
    ListElement { value: 48 }
    ListElement { value: 49 }
    ListElement { value: 50 }
    ListElement { value: 51 }
    ListElement { value: 52 }
    ListElement { value: 53 }
    ListElement { value: 54 }
    ListElement { value: 55 }
    ListElement { value: 56 }
    ListElement { value: 57 }
    ListElement { value: 58 }
    ListElement { value: 59 }
    ListElement { value: 60 }
}
