/**
 *
 */

var DEFAULT_MARGIN = 10;
var DEFAULT_RADIUS = 10;
var DEFAULT_BORDER_WIDTH = 2;
var DEFAULT_BAR_HEIGHT = 60;
var DEFAULT_BUTTON_WIDTH = 100;
var DEFAULT_BUTTON_HEIGHT = DEFAULT_BAR_HEIGHT;
var LABEL_HEIGHT = DEFAULT_BAR_HEIGHT;
var TOOL_BAR_HEIGHT = DEFAULT_BAR_HEIGHT * 1.5;
var SCROLL_BAR_WIDTH = 4;
var DEFAULT_FONT_PIXEL_SIZE = 22;
var SHADOW_OPACITY = 0.4;
var DEFAULT_TEXT_COLOR = "#dddddd";
var DEFAULT_BACKGROUND_COLOR = "black";
var DEFAULT_FOREGROUND_COLOR = DEFAULT_TEXT_COLOR;
var DARK_TEXT_COLOR = "#777777";
var DARK_TRANSLUCENT = "#cc000000";
var DEFAULT_BASE_COLOR = "#598fd8";
var DEFAULT_DARK_COLOR = "#295fa8";
var DEFAULT_LIGHT_COLOR = "#79aff8";
var ACCENT_BASE_COLOR = "#9ed859";
var ACCENT_DARK_COLOR = "#6ea829";
var ACCENT_LIGHT_COLOR = "#bef879";


// End of file.
